### ISSUE TITLE
Can't open the app on windows

### ISSUE THREAD

**Issue by Galaxy0Gamer** [rohitsangwan01/uni_control_hub#14]
**Describe the bug**
i open he app and get and get nothing.

**To Reproduce**
1. install the app
2. open the app
3. nothing happens

**Expected behavior**
the app to open normally

**Screenshots**
none, since nothing happens

**Desktop (please complete the following information):**
 - Windows 11

**Smartphone (please complete the following information):**
 - Samsung A51 
 - Android 13

Although when i first ran the app, i got some error about memory, then when i try to open it again, nothing happens.
I tried reinstalling, still the same thing.

**Comment by rohitsangwan01** [comment]
@Galaxy0Gamer can you compile app from Flutter, i have pushed few changes to the repo, but haven't released those yet

**Comment by rohitsangwan01** [comment]
@Galaxy0Gamer you can try [v0.0.5](https://github.com/rohitsangwan01/uni_control_hub/releases/) now

**Comment by Galaxy0Gamer** [comment]
@rohitsangwan01 v0.0.5 doesn't exist 
![image](https://github.com/user-attachments/assets/28b5b967-8af2-490a-ba8c-e656a3ffa987)

**Comment by Galaxy0Gamer** [comment]
> windows setup is little complex, you have to install VisualCode and all, but if you don't have flutter setup, then its fine, let me release an early builds of V0.0.5, you can try that in a while

i have flutter setup in the command prompt, but I don't know what to do next, "compile" is a scary looking word.

**Comment by rohitsangwan01** [comment]
@Galaxy0Gamer now V0.0.5 must be visible, and to build from sourceCode, you can checkout [this](https://github.com/rohitsangwan01/uni_control_hub?tab=readme-ov-file#developers-guide) section

**Comment by Galaxy0Gamer** [comment]
I got this error:
![image](https://github.com/user-attachments/assets/10a7750b-f74a-4f7e-988b-75f0f3219dc0)

**Comment by Galaxy0Gamer** [comment]
now it returned to nothing happening when i open it

**Comment by rohitsangwan01** [comment]
i wont be able to help you without logs, i think last hope would be to run app from source code, 
for this i guess you have already installed Flutter, 
now setup for windows development using [these](https://flutter-ko.dev/get-started/install/windows#windows-setup) instructions 
Once Flutter is set up, open project in any IDE of your choice,  run `flutter pub get` to download dependencies, and run `flutter run` to start the app

**Comment by Galaxy0Gamer** [comment]
how do i show you the logs..?

**Comment by rohitsangwan01** [comment]
@Galaxy0Gamer you can find the logs in  `C:\Users\YOUR_USER_NAME\AppData\Local\com.example\uni_control_hub` this path will change in future updates though
but for now logs file should be in this directory if generated

**Comment by Galaxy0Gamer** [comment]
there are no logs there, but this picture may be useful:
![image](https://github.com/user-attachments/assets/dd7fad45-ee4f-45f6-be6f-5bc5b723b5d0)

**Comment by Galaxy0Gamer** [comment]
It works now, after searching for what is MSVCP130.dll, i had to download the Microsoft Visual C++ 2015-2022, and it worked, it seems like it was outdated for me.
thanks

**Comment by rohitsangwan01** [comment]
Ohh great, btw I have also mentioned in readme section to install this, but seems like you directly got crash without proper error message

**Comment by Galaxy0Gamer** [comment]
yeah you should probably update it to say that if nothing happens to install it too.
