### ISSUE TITLE
Can't open the app

### ISSUE THREAD

**Issue by DanSega1** [rohitsangwan01/uni_control_hub#2]
when i'm trying to open the app i get this message
![image](https://github.com/rohitsangwan01/uni_control_hub/assets/108394291/6f203deb-9740-47b7-8b74-10d8aff9b08e)

**Comment by rohitsangwan01** [comment]
@DanSega1 are you on M1 or Intel mac ?

**Comment by DanSega1** [comment]
apple silicon M3 Pro

**Comment by rohitsangwan01** [comment]
Can you run this flutter project from, and get the Logs ?

**Comment by DanSega1** [comment]
I'm not sure when I made a mistake but, I can't use flutter_distributor to ![Screenshot 2024-06-25 at 17 52 27](https://github.com/rohitsangwan01/uni_control_hub/assets/108394291/e5e5536a-2329-44b2-82a5-fa319760b9e9)

**Comment by rohitsangwan01** [comment]
@DanSega1 you dont have to use flutter_distributor for debug builds

Install Flutter
Make sure Xcode is installed
and run: flutter run , command

**Comment by DanSega1** [comment]
This is my terminal error, it wasn't installing CocoaPods
```
❯ flutter run
Connected devices:
macOS (desktop) • macos • darwin-arm64 • macOS 14.5 23F79 darwin-arm64

No wireless devices were found.

[1]: macOS (macos)
Please choose one (or "q" to quit): 1
Launching lib/main.dart on macOS in debug mode...
Warning: CocoaPods not installed. Skipping pod install.
  CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart
  side.
  Without CocoaPods, plugins will not work on iOS or macOS.
  For more info, see https://flutter.dev/platform-plugins
To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.



Error: CocoaPods not installed or not in valid state.
```

**Comment by rohitsangwan01** [comment]
@DanSega1 you have to install CocoaPoods in mac manually for Mac or IOS development
if you have HomeBrew: `brew install cocoapods`

**Comment by DanSega1** [comment]
I did, i had an issue with xcode and fix it too.
but still have error in the build

```
❯ flutter run
Connected devices:
macOS (desktop) • macos • darwin-arm64 • macOS 14.5 23F79 darwin-arm64

Checking for wireless devices...

[1]: macOS (macos)
Please choose one (or "q" to quit): 1
Launching lib/main.dart on macOS in debug mode...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006030-000679520C28001C, name:My Mac }
{ platform:macOS, arch:x86_64, id:00006030-000679520C28001C, name:My Mac }
/Users/dansegal/.pub-cache/hosted/pub.dev/ble_peripheral-2.3.0/darwin/Classes/BlePeripheralPlugin.swift:36:27: warning: expression of type 'Bool' is unused
        peripheralManager.isAdvertising
        ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
/Users/dansegal/Downloads/uni_control_hub-main/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 14.5.99. (in target 'unihub' from project 'Pods')
Building macOS application...                                           
✓ Built build/macos/Build/Products/Debug/UniControlHub.app
dyld[75563]: Library not loaded: /opt/homebrew/opt/libusb/lib/libusb-1.0.0.dylib
  Referenced from: <6B960DFE-31AE-37DE-B591-28E1A2A1CD06> /Users/dansegal/Downloads/uni_control_hub-main/build/macos/Build/Products/Debug/UniControlHub.app/Contents/MacOS/UniControlHub
  Reason: tried: '/opt/homebrew/opt/libusb/lib/libusb-1.0.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libusb/lib/libusb-1.0.0.dylib' (no such file), '/opt/homebrew/opt/libusb/lib/libusb-1.0.0.dylib' (no such file)
Error waiting for a debug connection: The log reader stopped unexpectedly, or never started.
Error launching application on macOS.
```

**Comment by rohitsangwan01** [comment]
@DanSega1 Ahh this time the app built successfully, 
`✓ Built build/macos/Build/Products/Debug/UniControlHub.app`

but crashed like you mentioned,

and we got the crash reason as well
`Library not loaded: /opt/homebrew/opt/libusb/lib/libusb-1.0.0.dylib`

**Comment by DanSega1** [comment]
I install libusb and now it's working. I think you need to add the dependencies to the readme, it wasn't clear enough.

**Comment by rohitsangwan01** [comment]
> I install libusb and now it's working. I think you need to add the dependencies to the readme, it wasn't clear enough.

Ahh thats Great, i never faced this, probably because libusb was already installed for me, but i have already added the libusb binary within the application, to prevent this issue
Thank you for the efforts, i will try to dig in

**Comment by DanSega1** [comment]
I will play with it a little to check it out, I already notice that I can move the cursor only from my second monitor (mark it in red rectangle), if you could add support to choose from multiple monitors it will be tremendous.
![Screenshot 2024-06-26 at 10 43 14](https://github.com/rohitsangwan01/uni_control_hub/assets/108394291/38a72c15-5bdb-41df-b013-63224120378c)

**Comment by rohitsangwan01** [comment]
> I will play with it a little to check it out, I already notice that I can move the cursor only from my second monitor (mark it in red rectangle), if you could add support to choose from multiple monitors it will be tremendous.

You can change the direction to Lef, Right, Top or Down, but for now you can't choose Direction in middle of monitors
for app your both monitors is like a combined single monitor

internally this software uses [Synergy](https://github.com/symless/synergy-core) for mouse and keyboard sharing, if they support this, then it might be possible

**Comment by DanSega1** [comment]
They do support it, [https://symless.com/synergy/help/monitor-positioning-support](url)
