### ISSUE TITLE
I use 5g router with really good speed but mostly the cursor does not sync well

### ISSUE THREAD

**Issue by Uddhav07** [rohitsangwan01/uni_control_hub#21]

**Comment by Uddhav07** [comment]
it keeps bugging in, even if i lock it, it just confines to a 2x2 matrix in tab for some time

**Comment by rohitsangwan01** [comment]
@Uddhav07 There are many things involved in it, not just the Fast connection, like Ping and Adb response, and depends on Mobile as well, cant really do anything for now, but will try to improve connection with latency as low as possible
