### ISSUE TITLE
After installation nothing happens

### ISSUE THREAD

**Issue by otabekoff** [rohitsangwan01/uni_control_hub#27]
**Describe the bug**
I've installed this application on Windows 11 device of me. And didn't work. I've tried to open app manually many times. But no any window or any other GUI or toolbar icons.

**To Reproduce**
1. Download exe from github, 
2. Install
3. While install check all checkboxes
4. Nothing happens after run program or opening app. No UI.

**Expected behavior**
Expected to see the app opens UI or toolbar button to manage.

**Screenshots**
![image](https://github.com/user-attachments/assets/bda466cf-6ff7-4d38-b267-1ccae3db6ee3)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Smartphone (please complete the following information):**
It is not opening yet but phone connected to laptop with USB already if required:
 - Device: LG Wing
 - OS: Android 13

**Additional context**
Just not working.

**Comment by rohitsangwan01** [comment]
@otabekoff can you check if there are any log files on `C:\Users\YOUR_USERNAME\AppData\Local\com.rohit\uni_control_hub\` path ?
if yes, please share the logs

**Comment by otabekoff** [comment]
@rohitsangwan01 No logs in the logs folder. It is empty.

**Comment by rohitsangwan01** [comment]
@otabekoff please checkout [Windows section](https://github.com/rohitsangwan01/uni_control_hub?tab=readme-ov-file#windows), make sure Microsoft Visual C++ 2015-2022 is installed

**Comment by otabekoff** [comment]
@rohitsangwan01 I was installing it already. And it worked. But I've a problem. When using with Bandicam app, it is behaving weird. I was going to record a video about this app and use it in my one of app development videos for my course and also while that stream my phone screen together with my laptop. But it is behaving weird. When I click on phone, then the mouse is freezed there and cursor is coming back to laptop. No way to move cursor to phone again. But when I click on laptop, it also clicks on phone but not moving and no way to go it.

**Comment by otabekoff** [comment]
I’m closing the issue now, as it has been resolved. However, I wanted to leave some information for reference: the problem occurred when using Bandicam to record a custom rectangular area of the screen.

**Comment by rohitsangwan01** [comment]
@otabekoff It seems that the software also attempted to capture the mouse while UniControlHub was handling it, which caused the process to malfunction. I'll look into it further in the future."
