### ISSUE TITLE
Two mouse input devices for two devices seperately??

### ISSUE THREAD

**Issue by kabhinara** [rohitsangwan01/uni_control_hub#31]
Id like to have an option for my laptop trackpad work only for my laptop, whereas have the mouse be free or even just for the tablet.

Would basically turn the app into a usb hub extension software (the laptop becomes the hub)

Just having a hub + mouse and laptop connected to it is kinda janky i feel , so yeah 

Nice to have for a samsung tablet to take notes on :)

**Comment by kabhinara** [comment]
By the way, the app is awesome, thanks for helping us all out!

**Comment by rohitsangwan01** [comment]
@kabhinara Thankyou, but i dont think that's possible, because Desktop notifies us about combined Mouse movements

**Comment by rohitsangwan01** [comment]
If you have any ideas or questions, please feel free to reopen the issue or start a discussion. Your input is always welcome!
