### ISSUE TITLE
Inverted mouse scroll and wrong keyboard format (language). Is there anything I can do to fix these little annoyances?

### ISSUE THREAD

**Issue by pedro160901** [rohitsangwan01/uni_control_hub#6]
Inverted mouse scroll and wrong keyboard format (language). Is there anything I can do to fix these little annoyances?

**Comment by rohitsangwan01** [comment]
@pedro160901 i can add an option to invert mouse scroll, 
can you explain keyboard format issue, like what language issue you are facing ?

**Comment by pedro160901** [comment]
I am honored by your response, thank you in advance for your attention. I'm Brazilian, I use the ABNT pt-br format as my keyboard layout, some punctuations and accents (like "ç") are not being well accepted, but it's a much smaller problem.

**Comment by rohitsangwan01** [comment]
i can try to add keyboard mapping in the app, but can't say by when it will be implemented

**Comment by pedro160901** [comment]
I would be very happy with the inversion of the mouse scroll. Thanks in advance! If I can be of any use to you, just let me know.

**Comment by pedro160901** [comment]
@rohitsangwan01 Would you have an estimate for the scroll inversion? I'm looking forward to this update!

**Comment by rohitsangwan01** [comment]
@pedro160901 Added in [v0.0.3](https://github.com/rohitsangwan01/uni_control_hub/releases/tag/v0.0.3)
