### ISSUE TITLE
dll file not found

### ISSUE THREAD

**Issue by Uddhav07** [rohitsangwan01/uni_control_hub#7]
![image](https://github.com/user-attachments/assets/72a254bd-b834-467b-992c-a5dfb5e59a53)
![image](https://github.com/user-attachments/assets/3f5760b6-d819-4c68-a81c-3c2d80a7a019)
![image](https://github.com/user-attachments/assets/33698d2d-32d8-4448-abff-79b47abed65f)

**Comment by Uddhav07** [comment]
****

**Comment by rohitsangwan01** [comment]
@Uddhav07  The lack of these DLLs can be fixed by installing "Microsoft Visual C++ 2015 - 2022 Redistributable".
Download from the links below. I suggest you install both the x86 and x64 versions.
 x86: https://aka.ms/vs/17/release/vc_redist.x86.exe 
 x64: https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by Uddhav07** [comment]
> x86 and x64 versions.

win 11, 64 bit ofc

**Comment by Uddhav07** [comment]
![image](https://github.com/user-attachments/assets/8c8d8799-69fe-4b40-b575-cd6ee678d344)

**Comment by Uddhav07** [comment]
uhid not workin but aoa does, how can i make it wireless, using adb wireless?

**Comment by rohitsangwan01** [comment]
> uhid not workin but aoa does, how can i make it wireless, using adb wireless?

To use UHID, you have to install Adb first
You an follow [this](https://www.youtube.com/watch?v=trHNX9uHlBk) tutorial to install ADB
Adb mode requires USB Debugging to be enabled on your Android device, you can follow [this](https://www.youtube.com/watch?v=49I2DmzMP64https://www.youtube.com/watch?v=49I2DmzMP64) tutorial to enable usb debugging, and finally when usb debugging is enabled

Run this command in your CMD: `adb devices`, and if your device is listed, then all done
Now to enable wireless ADB mode, you can check how to connect Android device with Wireless ADB

**Comment by rohitsangwan01** [comment]
@Uddhav07 also please let me know how you fixed the above error, i will update readme for the fix

**Comment by Uddhav07** [comment]
> @Uddhav07 also please let me know how you fixed the above error, i will update readme for the fix

yeah i just downloaded the x64 file and installed, 2nd issue i solved by choosing aoa

**Comment by Uddhav07** [comment]
![image](https://github.com/user-attachments/assets/5f570527-eb09-452e-a808-282284607304)

**Comment by Uddhav07** [comment]
![image](https://github.com/user-attachments/assets/1d3774fa-fd2e-4d19-966d-7e3fed745653)

**Comment by Uddhav07** [comment]
im facing the above issue doing this

**Comment by Uddhav07** [comment]
![image](https://github.com/user-attachments/assets/f43b29ca-5ef1-46a6-81ec-ac138bf33bc6)
facing this issue, i think i sent this but it didnt go through

**Comment by rohitsangwan01** [comment]
Please share logs ( From Drawer -> Logs section -> Copy logs )

**Comment by Uddhav07** [comment]
![image](https://github.com/user-attachments/assets/9b9e5698-5557-4752-951a-b7f7a90d02e2)

**Comment by Uddhav07** [comment]
UniControlHub (v0.0.3) Logs: 

Killing previous process 10504
10504 Kill status: true
LibUsb Initialized for this platform
Killing previous process 10504
10504 Kill status: false
Trying to Start
Synergy Config: C:\Users\Uddhav\AppData\Local\com.example\uni_control_hub/synergy.conf
Address: 192.168.1.18:25800
Server started with pid: 10548
[2024-07-24T11:10:06] NOTE: clipboard sharing is disabled

[2024-07-24T11:10:06] NOTE: started server, waiting for clients

Trying to start adb server
Adb devices: [192.168.1.19:46193]
Trying to start adb server
Adb devices: [192.168.1.19:46193]
Trying to start adb server
Adb devices: [192.168.1.19:46193]
Killing Adb Server (if any)
AdbKillServer: 0
Killing Adb Server (if any)
AdbKillServer: 0
Trying to start adb server
Adb devices: [192.168.1.19:46193]
Trying to start adb server
Adb devices: [192.168.1.19:46193]
Trying to start adb server
Adb devices: [192.168.1.19:46193]
Server started at 192.168.1.18:4552
UHID Server started on port 4552

**Comment by Uddhav07** [comment]
this is log when i try to refresh in uhid twice

UniControlHub (v0.0.3) Logs: 

Trying to start adb server
Adb devices: [192.168.1.19:46193]
Server already started
Trying to start adb server
Adb devices: [192.168.1.19:46193]
Server already started

**Comment by Uddhav07** [comment]
![image](https://github.com/user-attachments/assets/6553284d-32d0-4fa1-81ef-9c3d08c700ce)
![image](https://github.com/user-attachments/assets/b69084fa-4766-470a-982f-04e9c50181e4)

**Comment by Uddhav07** [comment]
> ![image](https://private-user-images.githubusercontent.com/93899908/351691001-9b9e5698-5557-4752-951a-b7f7a90d02e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MTk3ODksIm5iZiI6MTcyMTgxOTQ4OSwicGF0aCI6Ii85Mzg5OTkwOC8zNTE2OTEwMDEtOWI5ZTU2OTgtNTU1Ny00NzUyLTk1MWEtYjdmN2E5MGQwMmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDExMTEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhYjU5YTk2YWVhYWRhYjRjNjg5MzYxMzE0MWQzYmExN2ZhMzM3YjczNzJlNzY2Nzc2ZmY1MDNmMjA4MDdjODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.spN7RWsao_rlx9hwwKWCbNIF36rKgacxYbjE_EyN_ts)

this was due to having the app open 2 places

**Comment by rohitsangwan01** [comment]
@Uddhav07 Got the issue, and pushed a new Fix, New version 0.0.4 will be available soon

**Comment by rohitsangwan01** [comment]
@Uddhav07 [v0.0.4l](https://github.com/rohitsangwan01/uni_control_hub/releases/tag/v0.0.4) is released now, please test and let me know if it works fine

**Comment by Uddhav07** [comment]
is there any way to close app into tray

**Comment by Uddhav07** [comment]
![image](https://github.com/user-attachments/assets/4979a1e2-ca44-4ee1-ac49-0b23532fe416)
UniControlHub (v0.0.4) Logs: 

Trying to start adb server
Adb devices: [192.168.1.17:34573]
Server already started
Server pushed to 192.168.1.17:34573
Server started on 192.168.1.17:34573
192.168.1.17:34573 Server stopped

**Comment by Uddhav07** [comment]
USB connection gives this
UniControlHub (v0.0.4) Logs: 

Killing Adb Server (if any)
AdbKillServer: 0
Killing Adb Server (if any)
AdbKillServer: 0
Added Client SAMSUNG_Android:R52WC08WG7Y
Synergy Client: Instance of 'SynergyClient'
Client SAMSUNG_Android:R52WC08WG7Y is connected: true
[2024-07-24T11:38:19] NOTE: accepted client connection

[2024-07-24T11:38:19] NOTE: client "Right" has connected

Trying to start adb server
Trying to start adb server
Trying to start adb server
Adb devices: []
Adb devices: []
Server already started
Server already started
Trying to start adb server
Adb devices: [R52WC08WG7Y]
Server already started
Server pushed to R52WC08WG7Y
Server started on R52WC08WG7Y
R52WC08WG7Y Server stopped

**Comment by rohitsangwan01** [comment]
i think this requires a separate issue, please try to reinstall v0.0.4 from scratch, if still getting same issue, please open a new issue, and also mention your android device and version

**Comment by Uddhav07** [comment]
> i think this requires a separate issue, please try to reinstall v0.0.4 from scratch, if still getting same issue, please open a new issue, and also mention your android device and version

yep i did fresh install

**Comment by rohitsangwan01** [comment]
@Uddhav07 is it working for you, if not, can you please open a new issue for UHID mode
